import type { Metadata } from "next";
import { Inter, Gruppo } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import Header from "@/components/header";

// const inter = Gruppo({ subsets: ["latin"] });
const inter = Gruppo({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-wave`}>
        <div className="min-h-screen w-full">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
